# Generated by Django 4.2 on 2025-06-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChannelReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Slack user ID', max_length=50)),
                ('channel_id', models.CharField(help_text='Slack channel ID', max_length=50)),
                ('last_read_ts', models.CharField(help_text='Slack timestamp of last read message', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='userchannelreadstate',
            index=models.Index(fields=['user_id', 'channel_id'], name='bot_usercha_user_id_58bd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='userchannelreadstate',
            index=models.Index(fields=['updated_at'], name='bot_usercha_updated_33ed4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchannelreadstate',
            unique_together={('user_id', 'channel_id')},
        ),
    ]
